import { expect, go, test } from './fixtures';

/** Every module renders its page title with no runtime errors (all pre-redesign routes kept, plus the intelligence pages). */
const ROUTES: [string, RegExp][] = [
  ['', /Mission Control/],
  ['dashboards', /Dashboards/],
  ['pm', /My Workspace/],
  ['activities', /Activities/],
  ['products', /Products & Platforms/],
  ['configurator', /Configurator/],
  ['platformization', /Platformization/],
  ['customers', /Customers/],
  ['companies', /Companies/],
  ['opportunities', /Opportunities/],
  ['inquiry', /customer inquiry/],
  ['requirements', /Requirements/],
  ['traceability', /Traceability/],
  ['applications', /Applications/],
  ['materials', /Materials/],
  ['laser', /Laser Platform/],
  ['laser-sources', /Laser Sources/],
  ['optics', /Optics/],
  ['galvo', /Galvo/],
  ['calculators', /Calculators/],
  ['formulas', /Formulas/],
  ['process', /Process Engineering/],
  ['poc', /POCs/],
  ['doe', /DOE Studies/],
  ['machines', /Machines/],
  ['architecture', /Architecture/],
  ['modules', /Modules/],
  ['reuse', /What Can We Reuse/],
  ['semiconductor', /Semiconductor Intelligence/],
  ['equipment-buyer', /Equipment Buyer/],
  ['suppliers', /Suppliers/],
  ['rfq', /RFQs/],
  ['procurement', /Procurement/],
  ['bom', /BOM/],
  ['items', /Components/],
  ['cost', /Cost/],
  ['projects', /Projects/],
  ['gates', /Design Gates/],
  ['quality', /Risk & FMEA/],
  ['decisions', /Engineering Decisions/],
  ['changes', /Change Requests/],
  ['fat-sat', /FAT/],
  ['production-release', /Production Release/],
  ['localization', /Localization/],
  ['technology', /Technology Radar/],
  ['roadmap', /Roadmap/],
  ['global', /Global Intelligence/],
  ['knowledge', /Engineering Knowledge/],
  ['search', /Search/],
  ['memory', /Engineering Memory/],
  ['missing', /What Is Missing/],
  ['changed', /What Changed/],
  ['graph', /Knowledge Graph/],
  ['evidence', /Evidence/],
  ['lessons', /Lessons Learned/],
  ['ai', /AI context/i],
  ['copilot', /TEAL Copilot/],
  ['ai-engine', /AI Engine Control Center/],
  ['ai-configure', /AI Product Configurator/],
  ['service', /Field Service/],
  ['admin', /Data Manager/],
  ['data-quality', /Data Health/],
  ['reports', /Reports/],
  ['help', /Help Center/],
  ['legacy', /Legacy Applications/],
  ['compare', /Compare/],
  ['ask', /Ask Intelligence/],
  ['duplicates', /Duplicates/],
  ['supplier-risk', /Supplier Risk/],
  ['units', /Unit Converter/],
  ['rooms', /Rooms/],
  ['domains', /Domains/],
  ['domains/laser', /Laser & Photonics/],
  ['domains/electronics', /Electronics & EMS/],
  ['domains/semiconductor', /Semiconductor/],
  ['domains/battery', /Battery & New Energy/],
  ['domains/automation', /Industrial Automation/],
  ['domains/advanced-manufacturing', /Advanced Manufacturing/],
  ['cross-domain', /Cross-Domain Map/],
  ['solution', /Application Engine/],
  ['product-architecture', /Product Architecture/],
  ['development', /Product Development/],
  ['capture', /Requirement Capture/],
  ['execution', /Execution/],
  ['documents', /Documents/],
  ['value', /Business Value/],
  ['opportunity-matrix', /Opportunity Matrix/],
  ['import-export', /Import \/ Export/],
  ['settings', /Settings/],
  ['use-cases', /Use Cases/],
  ['partners', /Partners/],
  ['articles', /Knowledge Articles/],
  ['equipment', /Equipment/],
  ['room/prd-markf', /Mark F-Series/],
  ['leads', /LeadConnect/],
  ['business-case', /Market & Business Case/],
  ['record/prd-semispm', /Semi SPM/],
  ['record/gate-g3', /G3/],
  ['studio', /Equipment Simulation Studio/],
  ['studio?tab=library', /Equipment Simulation Studio/],
  ['studio?tab=compare', /Equipment Simulation Studio/],
  ['studio?tab=disruption', /Equipment Simulation Studio/],
  ['studio/sim-demo-pcb-a', /PCB laser marking — Scenario A/],
  ['studio/sim-demo-semi-marking', /Semiconductor package marking/],
  ['component-datasheets', /Component Datasheets/],
  ['studio/sim-demo-laser-marker?tab=machine3d', /Semi-automatic laser marking machine/],
  ['engineering-db', /Global Engineering Database/],
  ['engineering-db?tab=manufacturers', /Global Engineering Database/],
  ['engineering-db?tab=specs', /Global Engineering Database/],
  ['engineering-db?tab=compatibility', /Global Engineering Database/],
  ['engineering-db?tab=compare&ids=prt-demo-mopa-20,prt-demo-mopa-30', /Global Engineering Database/],
  ['engineering-db?tab=analytics', /Global Engineering Database/],
  ['engineering-db?tab=sources', /Global Engineering Database/],
  ['engineering-db?tab=overlay', /Global Engineering Database/],
  ['engineering-db?discipline=Vision', /Global Engineering Database/],
  ['data-review', /Data Review Center/],
  ['data-review?queue=Conflicting', /Data Review Center/],
  ['data-review?queue=Duplicate', /Data Review Center/],
  ['data-review?queue=Changed', /Data Review Center/],
  ['requirements-quality', /Requirement Quality/],
  ['requirements-quality?tab=coverage', /Requirement Quality/],
  ['requirements-quality?tab=baselines', /Requirement Quality/],
  ['document-library', /Technical Documents/],
  ['actions', /Action Center/],
  ['recipes', /Process Recipes/],
  ['verification', /Verification & Validation/],
  ['quality-records', /Quality Records/],
  ['dfmea', /DFMEA/],
  ['pfmea', /PFMEA/],
  ['ncr', /NCR/],
  ['capa', /CAPA/],
  ['8d', /8D/],
  ['control-plan', /Control Plans/],
  ['inspection-plan', /Inspection Plans/],
  ['service?tab=machines', /Field Service/],
  ['applications?process=Welding', /Applications/],
  ['record/prt-demo-mopa-50', /DEMO fiber MOPA laser 50 W/],
  ['record/eqt-pcb-laser-marking', /PCB Laser Marking/],
  ['record/sim-demo-pcb-b', /Scenario B/],
  ['record/spd-wavelength', /Wavelength/],
  ['record/cpr-laser-ftheta-wavelength', /f-theta/],
];

test.describe('every module renders without runtime errors', () => {
  for (const [route, title] of ROUTES) {
    test(`/${route}`, async ({ page }) => {
      await go(page, route);
      await expect(page.locator('main h1').first()).toHaveText(title);
      await expect(page.locator('main h1')).toHaveCount(1);
    });
  }
});

test('unknown routes show a helpful not-found page', async ({ page }) => {
  await page.goto('./#/does-not-exist');
  await expect(page.getByText('Page not found')).toBeVisible();
});

test('data types stay visible: demo records are labelled', async ({ page }) => {
  await go(page, 'record/prj-demo-c2i');
  await expect(page.getByText(/Demo record/)).toBeVisible();
});
