/**
 * Embed the three legacy apps, functionally unchanged, under public/legacy/ so they keep working
 * inside the OS deployment (spec §7: do not delete useful functionality, do not blindly rewrite).
 *
 * Source: LEGACY_ROOT (default ../songarajatin225-a11y) containing clones of
 *   teal-laser-product-sim-2 · teal-cost-platform-2 · product-tracker-
 *
 * Sanitisation applied to the copies (and nothing else):
 *   - Laser simulator: the cosmetic admin PIN is removed (a PIN in page source is not security).
 *   - Cost platform: seeded projects and audit trail are emptied (they paired real customer
 *     names with fabricated jobs and prices); the customer master is emptied. Templates, item
 *     master (DEMO prices), rates and config are kept so the app still works.
 *   - PM tracker: copied as is (its sample data is fictional, @example.com, tagged isSample).
 *
 * Run: LEGACY_ROOT=/path/to/clones npx tsx scripts/migration/embedLegacyApps.ts
 */
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { ROOT } from '../lib/dataset';

const LEGACY_ROOT = resolve(process.env.LEGACY_ROOT ?? join(ROOT, '..', 'songarajatin225-a11y'));
const OUT = join(ROOT, 'public', 'legacy');

const APPS = [
  { repo: 'teal-laser-product-sim-2', dir: 'laser-simulator', files: ['index.html', 'data.json', 'README.md'] },
  { repo: 'teal-cost-platform-2', dir: 'cost-platform', files: ['index.html', 'encrypt.html', 'assets', 'data', 'README.md'] },
  { repo: 'product-tracker-', dir: 'pm-tracker', files: ['index.html', 'activities.html', 'applications.html', 'competitors.html', 'customers.html', 'daily-log.html', 'dashboard.html', 'localization.html', 'meetings.html', 'products.html', 'reports.html', 'samples.html', 'settings.html', 'suppliers.html', 'weekly-review.html', 'assets', 'css', 'js', 'data', 'README.md'] },
] as const;

function main() {
  if (!existsSync(LEGACY_ROOT)) {
    console.error(`LEGACY_ROOT not found: ${LEGACY_ROOT}. Clone the legacy repositories there first.`);
    process.exit(1);
  }
  for (const app of APPS) {
    const src = join(LEGACY_ROOT, app.repo);
    const dst = join(OUT, app.dir);
    rmSync(dst, { recursive: true, force: true });
    mkdirSync(dst, { recursive: true });
    for (const f of app.files) {
      if (!existsSync(join(src, f))) throw new Error(`${app.repo}/${f} missing`);
      cpSync(join(src, f), join(dst, f), { recursive: true });
    }
    writeFileSync(join(dst, '.nojekyll'), '');
  }

  // Laser simulator — remove the cosmetic admin PIN.
  const simData = join(OUT, 'laser-simulator', 'data.json');
  const sim = JSON.parse(readFileSync(simData, 'utf8'));
  if (sim.rules && 'adminPin' in sim.rules) sim.rules.adminPin = '';
  else if (sim.pricing && 'adminPin' in sim.pricing) sim.pricing.adminPin = '';
  else walkRemovePin(sim);
  writeFileSync(simData, JSON.stringify(sim, null, 2) + '\n');
  const simHtml = join(OUT, 'laser-simulator', 'index.html');
  const html = readFileSync(simHtml, 'utf8');
  const cleaned = html.replace(/adminPin:'[^']*'/, "adminPin:''");
  if (cleaned === html) throw new Error('adminPin default not found in simulator index.html');
  writeFileSync(simHtml, cleaned);
  const simReadme = join(OUT, 'laser-simulator', 'README.md');
  writeFileSync(simReadme, readFileSync(simReadme, 'utf8').replace(/Enter the PIN — `[^`]*` by default, changeable under \*\*Pricing rules\*\*\./, 'No PIN in this embedded copy (the original PIN was cosmetic — readable in page source). Edits stay in this browser until data.json is exported and committed.'));

  // Cost platform — empty seeded projects, audit and customer master.
  const projPath = join(OUT, 'cost-platform', 'data', 'projects.json');
  const proj = JSON.parse(readFileSync(projPath, 'utf8'));
  writeFileSync(projPath, JSON.stringify({ ...proj, projects: [], audit: [] }, null, 2) + '\n');
  const mastersPath = join(OUT, 'cost-platform', 'data', 'masters.json');
  const masters = JSON.parse(readFileSync(mastersPath, 'utf8'));
  writeFileSync(mastersPath, JSON.stringify({ ...masters, customer: [] }, null, 2) + '\n');

  writeFileSync(
    join(OUT, 'README.md'),
    `# Legacy apps (embedded)

Copies of the three legacy TEAL apps, served by the OS deployment at \`/legacy/<app>/\`.
They are generated by \`scripts/migration/embedLegacyApps.ts\` — do not edit by hand.

| App | Source repository | Changes in this copy |
|---|---|---|
| laser-simulator | songarajatin225-a11y/teal-laser-product-sim-2 | cosmetic admin PIN removed |
| cost-platform | songarajatin225-a11y/teal-cost-platform-2 | seeded projects, audit trail and customer master emptied |
| pm-tracker | songarajatin225-a11y/product-tracker- | none |

Each app keeps its own browser storage (IndexedDB / localStorage) on the shared GitHub Pages
origin, which is what lets the OS import your legacy working data in the browser
(Admin → Import from legacy apps). Prices in these apps are DEMO / ESTIMATE seed values.
`,
  );
  console.log(`Embedded ${APPS.length} legacy apps into ${OUT}`);
}

function walkRemovePin(o: unknown): void {
  if (!o || typeof o !== 'object') return;
  for (const [k, v] of Object.entries(o as Record<string, unknown>)) {
    if (k === 'adminPin') (o as Record<string, unknown>)[k] = '';
    else walkRemovePin(v);
  }
}

main();
