import clsx from 'clsx';
import { AlertTriangle, Ban, CheckCircle2, CircleDashed, CircleDot, Clock, FileQuestion, FlaskConical, Link2, PencilLine, Sparkles, type LucideIcon } from 'lucide-react';
import type { DataType, VerificationStatus } from '../domain/common';
import type { RecordOrigin } from '../repositories/types';
import { Badge, type Tone } from './ui';

/*
 * Central status + data-trust language (spec §36–§37, §85). Screens never invent their own
 * status words or colours: they pass the domain value here. Every badge carries text + icon,
 * so colour is never the only signal.
 */

const DT: Record<DataType, { label: string; tone: Tone; title: string }> = {
  TEAL_INTERNAL: { label: 'TEAL', tone: 'accent', title: 'TEAL internal data (handbooks, catalogue, TEAL records)' },
  PUBLIC: { label: 'Public', tone: 'info', title: 'Public information' },
  EXTERNAL: { label: 'External', tone: 'info', title: 'External data, curated through the reviewed ingestion pipeline' },
  DEMO: { label: 'Demo', tone: 'demo', title: 'Demonstration data — fictional, not real customer or engineering data' },
  CALCULATED: { label: 'Calculated', tone: 'ok', title: 'Calculated from other data' },
  INFERRED: { label: 'Inferred', tone: 'draft', title: 'Inferred / generated by a rule — a draft until validated' },
  AI_GENERATED: { label: 'AI-generated', tone: 'draft', title: 'AI-generated — requires review' },
  USER_CREATED: { label: 'User', tone: 'neutral', title: 'Created by a user or imported from a legacy app' },
};

export const dataTypeLabel = (t?: string) => DT[t as DataType]?.label ?? 'Unknown';

export function DataTypeBadge({ t }: { t?: string }) {
  const d = DT[t as DataType];
  return (
    <Badge tone={d?.tone ?? 'neutral'} title={d?.title ?? 'Unknown data type'}>
      {d?.label ?? 'Unknown'}
    </Badge>
  );
}

const VS: Record<VerificationStatus, { label: string; tone: Tone; icon: LucideIcon; title: string }> = {
  VERIFIED: { label: 'Verified', tone: 'ok', icon: CheckCircle2, title: 'Verified by a reviewer' },
  SOURCE_DOCUMENTED: { label: 'Source linked', tone: 'accent', icon: Link2, title: 'Documented in a cited source; not independently verified' },
  CALCULATED: { label: 'Calculated', tone: 'ok', icon: CircleDot, title: 'Computed by a documented formula' },
  INFERRED: { label: 'Inferred', tone: 'draft', icon: Sparkles, title: 'Inferred by a rule' },
  DRAFT: { label: 'Draft', tone: 'draft', icon: PencilLine, title: 'Draft — not yet validated' },
  ASSUMPTION: { label: 'Assumption', tone: 'warn', icon: FileQuestion, title: 'An assumption — confirm before relying on it' },
  UNKNOWN: { label: 'Unverified', tone: 'neutral', icon: CircleDashed, title: 'Verification status unknown' },
  CONFLICTED: { label: 'Conflicted', tone: 'bad', icon: AlertTriangle, title: 'Sources disagree — review required' },
  STALE: { label: 'Stale', tone: 'warn', icon: Clock, title: 'Older than the freshness threshold' },
};

export function VerificationBadge({ v }: { v?: string }) {
  const d = VS[v as VerificationStatus] ?? VS.UNKNOWN;
  return (
    <Badge tone={d.tone} title={d.title}>
      <d.icon className="size-3" aria-hidden />
      {d.label}
    </Badge>
  );
}

/**
 * Compact trust indicator (spec §37, §85): one quiet line — verification icon + data type +
 * source/last-verified on hover. Used on cards where two full badges would be noise.
 */
export function DataConfidence({ dataType, verification, source, lastVerified, className }: { dataType?: string; verification?: string; source?: string; lastVerified?: string; className?: string }) {
  const v = VS[verification as VerificationStatus] ?? VS.UNKNOWN;
  const d = DT[dataType as DataType];
  const title = [v.title, d?.title, source ? `Source: ${source}` : '', lastVerified ? `Last verified ${lastVerified}` : ''].filter(Boolean).join(' · ');
  return (
    <span title={title} className={clsx('inline-flex items-center gap-1 text-micro text-ink-3', className)}>
      <v.icon className={clsx('size-3.5', v.tone === 'ok' && 'text-ok', v.tone === 'accent' && 'text-accent', v.tone === 'bad' && 'text-bad', (v.tone === 'warn' || v.tone === 'draft') && 'text-warn')} aria-hidden />
      <span>{v.label}</span>
      {d && (
        <>
          <span aria-hidden>·</span>
          <span className={clsx(d.tone === 'demo' && 'font-medium text-demo')}>{d.label}</span>
        </>
      )}
    </span>
  );
}

export function OriginBadge({ o }: { o?: RecordOrigin }) {
  if (!o || o === 'MASTER') return null;
  return (
    <Badge tone="draft" title="Stored only in this browser. Permanent repository update requires a GitHub commit.">
      <PencilLine className="size-3" aria-hidden />
      {o === 'LOCAL_NEW' ? 'Local draft · new' : 'Local draft'}
    </Badge>
  );
}

/** Domain status words → one tone + icon vocabulary. Unknown words render neutral. */
const STATUS: Record<string, Tone> = {
  Completed: 'ok', Complete: 'ok', Won: 'ok', GO: 'ok', PASS: 'ok', Closed: 'ok', Resolved: 'ok', Awarded: 'ok', Feasible: 'ok', Verified: 'ok', Accepted: 'ok', Released: 'ok',
  'In Progress': 'info', Active: 'info', Analysis: 'info', Issued: 'info', Proposal: 'info', Negotiation: 'info', Feasibility: 'info', POC: 'info', Requirement: 'info', Discovery: 'info',
  Blocked: 'bad', Lost: 'bad', 'NO-GO': 'bad', FAIL: 'bad', 'Not feasible': 'bad', Critical: 'bad', Conflicted: 'bad', Cancelled: 'bad',
  Open: 'warn', Waiting: 'warn', 'GO WITH CONDITIONS': 'warn', 'Samples Awaited': 'warn', High: 'warn', 'PASS WITH DEVIATION': 'warn', Mitigating: 'warn', 'At Risk': 'warn', Stale: 'warn',
  Adopt: 'ok', Evaluate: 'info', Monitor: 'neutral', Emerging: 'accent', Avoid: 'bad',
  Draft: 'draft', Estimated: 'draft', Lead: 'neutral', Planned: 'neutral', 'Not Started': 'neutral', PENDING: 'neutral', 'NOT RUN': 'neutral', Undecided: 'neutral', Deprecated: 'neutral', Obsolete: 'neutral', Unknown: 'neutral',
};
const TONE_ICON: Partial<Record<Tone, LucideIcon>> = { ok: CheckCircle2, bad: Ban, warn: AlertTriangle, info: CircleDot, draft: PencilLine, demo: FlaskConical };

export const statusTone = (s?: string | null): Tone => (s ? (STATUS[s] ?? 'neutral') : 'neutral');

export function StatusBadge({ s }: { s?: string | null }) {
  if (!s) return null;
  const tone = statusTone(s);
  const Icon = TONE_ICON[tone];
  return (
    <Badge tone={tone}>
      {Icon && <Icon className="size-3" aria-hidden />}
      {s}
    </Badge>
  );
}
