import type { DataType, VerificationStatus } from '../domain/common';
import type { RecordOrigin } from '../repositories/types';
import { Badge, type Tone } from './ui';

const DT_TONE: Record<DataType, Tone> = {
  TEAL_INTERNAL: 'accent',
  PUBLIC: 'info',
  EXTERNAL: 'info',
  DEMO: 'demo',
  CALCULATED: 'ok',
  INFERRED: 'draft',
  AI_GENERATED: 'draft',
  USER_CREATED: 'neutral',
};
const DT_TITLE: Record<DataType, string> = {
  TEAL_INTERNAL: 'TEAL internal data (handbooks, catalogue, TEAL records)',
  PUBLIC: 'Public information',
  EXTERNAL: 'External data (curated through the ingestion pipeline)',
  DEMO: 'Demonstration data — fictional, not real customer or engineering data',
  CALCULATED: 'Calculated by the OS from other data',
  INFERRED: 'Inferred / generated by a rule — a DRAFT until validated',
  AI_GENERATED: 'AI-generated — requires review',
  USER_CREATED: 'Created by a user in this workspace or imported from a legacy app',
};

export function DataTypeBadge({ t }: { t?: string }) {
  const k = (t ?? 'UNKNOWN') as DataType;
  return (
    <Badge tone={DT_TONE[k] ?? 'neutral'} title={DT_TITLE[k] ?? 'Unknown data type'}>
      {k === 'TEAL_INTERNAL' ? 'TEAL' : k.replace('_', ' ')}
    </Badge>
  );
}

const VS_TONE: Record<VerificationStatus, Tone> = {
  VERIFIED: 'ok',
  SOURCE_DOCUMENTED: 'accent',
  CALCULATED: 'ok',
  INFERRED: 'draft',
  DRAFT: 'draft',
  ASSUMPTION: 'warn',
  UNKNOWN: 'neutral',
  CONFLICTED: 'bad',
  STALE: 'warn',
};

export function VerificationBadge({ v }: { v?: string }) {
  const k = (v ?? 'UNKNOWN') as VerificationStatus;
  return (
    <Badge tone={VS_TONE[k] ?? 'neutral'} title={`Verification: ${k}`}>
      {k.replace('_', ' ')}
    </Badge>
  );
}

export function OriginBadge({ o }: { o?: RecordOrigin }) {
  if (!o || o === 'MASTER') return null;
  return (
    <Badge tone="draft" title="Stored only in this browser. Permanent repository update requires a GitHub commit.">
      {o === 'LOCAL_NEW' ? 'LOCAL DRAFT · NEW' : 'LOCAL DRAFT'}
    </Badge>
  );
}

const STATUS_TONE: Record<string, Tone> = {
  Completed: 'ok', Complete: 'ok', Won: 'ok', GO: 'ok', PASS: 'ok', Closed: 'ok', Resolved: 'ok', Awarded: 'ok', Feasible: 'ok',
  'In Progress': 'info', Active: 'info', Analysis: 'info', Issued: 'info',
  Blocked: 'bad', Lost: 'bad', 'NO-GO': 'bad', FAIL: 'bad', Open: 'warn', 'Not feasible': 'bad', Critical: 'bad',
  Waiting: 'warn', 'GO WITH CONDITIONS': 'warn', 'Samples Awaited': 'warn', High: 'warn', 'PASS WITH DEVIATION': 'warn', Mitigating: 'warn',
  Draft: 'draft', Planned: 'neutral', 'Not Started': 'neutral', PENDING: 'neutral', 'NOT RUN': 'neutral', Undecided: 'neutral',
};
export function StatusBadge({ s }: { s?: string | null }) {
  if (!s) return null;
  return <Badge tone={STATUS_TONE[s] ?? 'neutral'}>{s}</Badge>;
}
