import { useMemo, useState } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { RecordLink } from '../../components/RecordLink';
import { Badge, Button, Card, EmptyState, Field, Input, KV, Notice, PageHeader, Select, Table, Textarea, Unknown } from '../../components/ui';
import type { AnyRecord } from '../../domain';
import type { Application, Company, GateDefinition, Material, Supplier } from '../../domain/entities';
import { useData, useEngine } from '../../hooks/useData';
import { newLocalId, repo } from '../../repositories';
import { buildDraftPackage, type DraftPackage } from '../../services/inquiry';
import { fmtDate } from '../../utils/dates';

const EXAMPLES = [
  'Need inline laser marking of semiconductor packages, 2D code, high throughput, automatic handling, vision inspection and MES communication. Customer supplies laser.',
  'CO2 laser marking of PCB panels with 2D codes on solder mask, inline SMEMA conveyor, code grading, 400 UPH.',
  'Laser welding of copper busbars on prismatic battery modules, weld monitoring, high volume.',
  'UV laser cutting of flexible PCB (polyimide coverlay), minimal HAZ, low volume prototype.',
];

const inr = (v: number | null | undefined) => (v == null ? null : `₹ ${Math.round(v).toLocaleString('en-IN')}`);

function PackagePreview({ pkg }: { pkg: DraftPackage }) {
  const f = pkg.facts;
  return (
    <div className="space-y-3">
      <Notice tone="draft">Everything below is a DRAFT generated by documented rules. Nothing is validated; UNKNOWN values stay UNKNOWN and become open questions.</Notice>
      <div className="grid grid-cols-1 gap-3 xl:grid-cols-2">
        <Card title="1 · What the inquiry says (parsed)">
          <KV
            items={[
              ['Process families', Object.keys(f.families).length ? Object.entries(f.families).map(([k, n]) => `${k} (${n})`).join(', ') : <Unknown />],
              ['Materials', Object.keys(f.materials).length ? Object.keys(f.materials).join(', ') : <Unknown label="UNKNOWN — ask customer" />],
              ['Industry', f.industry ?? <Unknown />],
              ['Needs → modules', f.needs.length ? f.needs.join(', ') : '—'],
              ['Care signals', f.cares.join(', ') || '—'],
              ['Scale', f.scale ?? '—'],
              ['Rate', f.perHour ? `${f.perHour} parts/h` : <Unknown label="UNKNOWN — not stated" />],
              ['Customer-supplied laser', f.customerSuppliesLaser ? 'Yes' : 'No'],
              ['Matched terms', <span key="t" className="text-meta text-ink-3">{f.matchedTerms.join(', ')}</span>],
            ]}
          />
        </Card>
        <Card title="2 · Platform candidates (reuse first)">
          {pkg.matches.length ? (
            <ol className="space-y-2">
              {pkg.matches.map((m, i) => (
                <li key={m.product.id}>
                  <div className="flex flex-wrap items-center gap-1.5">
                    <Badge tone={i === 0 ? 'ok' : 'neutral'}>{i === 0 ? 'Selected' : `#${i + 1}`}</Badge>
                    <RecordLink id={m.product.id} />
                    <span className="text-ink-3">· {m.product.applications.find((a) => a.key === m.appKey)?.name}</span>
                    <span className="num text-micro text-ink-3">score {m.score}</span>
                  </div>
                  <div className="pl-1 text-meta text-ink-2">Why: {m.why.map((w) => `${w.t} — ${w.d}`).join('; ')}</div>
                </li>
              ))}
            </ol>
          ) : (
            <EmptyState title="No catalogue platform matched" explain="This looks like a new development. Capture requirements and plan a feasibility POC." />
          )}
          <p className="mt-2 text-meta text-ink-3">Scoring: legacy configurator advisor + two OS rules (process credit, specialist platform). Candidates are not ranked as “best”.</p>
        </Card>
      </div>
      <Card title={`3 · Draft requirements (${pkg.requirements.length})`}>
        <Table head={['ID', 'Requirement', 'Type', 'Priority', 'Verify by', 'Acceptance']}>
          {pkg.requirements.map((r) => (
            <tr key={r.id}>
              <td className="num">{r.code}</td>
              <td>{r.name}</td>
              <td>{r.category}</td>
              <td>{r.priority}</td>
              <td>{r.verification_method}</td>
              <td className="text-ink-2">{r.acceptance_criterion ?? <Unknown />}</td>
            </tr>
          ))}
        </Table>
      </Card>
      <div className="grid grid-cols-1 gap-3 xl:grid-cols-2">
        <Card title="4 · Application & process candidates">
          {pkg.application && (
            <p className="mb-2">
              Application: <RecordLink id={pkg.application.id} /> — <span className="text-ink-2">{pkg.application.rationale}</span>
            </p>
          )}
          <Table head={['Platform', 'Application', 'Source', 'Regime', 'Spot µm']} dense>
            {pkg.processCandidates.map((p, i) => (
              <tr key={i}>
                <td>{p.product}</td>
                <td>{p.application}</td>
                <td>{p.source}</td>
                <td>{p.regime ?? <Unknown />}</td>
                <td className="num">{p.spot_um?.toFixed(0) ?? '—'}</td>
              </tr>
            ))}
          </Table>
          <p className="mt-1 text-meta text-ink-3">Process candidates, not a guaranteed process. Spot size is a diffraction-limited estimate.</p>
        </Card>
        <Card title="5 · Architecture & reusable modules">
          {pkg.configuration ? (
            <>
              <KV
                items={[
                  ['Designation', <span key="d" className="num">{pkg.configuration.designation}</span>],
                  ['Price band (ESTIMATE)', pkg.configuration.snapshot?.price_band_inr ? `${inr(pkg.configuration.snapshot.price_band_inr[0])} – ${inr(pkg.configuration.snapshot.price_band_inr[1])}` : <Unknown />],
                  ['Compatibility', `${pkg.configuration.snapshot?.warnings.length ?? 0} warning(s) / unknown(s)`],
                ]}
              />
              <ul className="mt-2 grid grid-cols-1 gap-0.5 sm:grid-cols-2">
                {pkg.reusableModules.map((m) => (
                  <li key={m.key} className="flex items-center gap-1.5">
                    <Badge tone={m.status === 'Standard content' ? 'ok' : m.status === 'Requested need' ? 'accent' : 'neutral'}>{m.status}</Badge>
                    {m.name}
                  </li>
                ))}
              </ul>
            </>
          ) : (
            <Unknown label="No configuration — no platform matched" />
          )}
        </Card>
      </div>
      <div className="grid grid-cols-1 gap-3 xl:grid-cols-2">
        <Card title="6 · POC & DOE plan">
          {pkg.poc ? (
            <>
              <p className="mb-1">{pkg.poc.objective}</p>
              <p className="text-meta text-ink-2">
                DOE: {pkg.doe?.factors.map((x) => `${x.name} [${x.levels.join(', ')}] ${x.unit ?? ''}`).join(' × ')} → <b>{pkg.doe?.runs.length} runs</b>; responses: {pkg.doe?.responses.map((r) => r.name).join(', ')}. Results empty until measured.
              </p>
            </>
          ) : (
            <Unknown />
          )}
        </Card>
        <Card title="7 · Preliminary BOM & cost assumptions">
          {pkg.bom ? (
            <Table head={['Line', 'Description', 'Unit cost', 'Basis']} dense>
              {pkg.bom.lines.map((l) => (
                <tr key={l.line_id}>
                  <td className="num">{l.line_id}</td>
                  <td>{l.description}</td>
                  <td className="num">{l.unit_cost == null ? <Unknown /> : inr(l.unit_cost)}</td>
                  <td>
                    <Badge tone={l.cost_basis === 'ESTIMATE' ? 'warn' : 'neutral'}>{l.cost_basis}</Badge>
                  </td>
                </tr>
              ))}
            </Table>
          ) : (
            <Unknown />
          )}
          <ul className="mt-2 list-disc pl-5 text-meta text-ink-2">
            {pkg.costModel?.assumptions?.map((a) => (
              <li key={a}>{a}</li>
            ))}
          </ul>
        </Card>
      </div>
      <div className="grid grid-cols-1 gap-3 xl:grid-cols-3">
        <Card title="8 · Supplier requirements">
          <ul className="space-y-1.5">
            {pkg.supplierNeeds.map((s) => (
              <li key={s.need}>
                <div className="font-medium">{s.need}</div>
                <div className="text-meta text-ink-2">{s.candidates.length ? s.candidates.map((c) => c.name).join(', ') : <Unknown label="no supplier on record" />}</div>
              </li>
            ))}
          </ul>
          <p className="mt-1 text-micro text-ink-3">Candidates only: handbook-named suppliers and DEMO vendor master — no quotation implied.</p>
        </Card>
        <Card title="9 · Risks">
          <ul className="list-disc space-y-0.5 pl-5">
            {pkg.risks.map((r) => (
              <li key={r.id}>{r.name}</li>
            ))}
          </ul>
        </Card>
        <Card title="10 · Open questions">
          <ul className="list-disc space-y-0.5 pl-5">
            {pkg.openQuestions.map((q) => (
              <li key={q}>{q}</li>
            ))}
          </ul>
        </Card>
      </div>
      <div className="grid grid-cols-1 gap-3 xl:grid-cols-2">
        <Card title="11 · G0 checklist (Automation Handbook gate definition)">
          <ul className="space-y-0.5">
            {pkg.g0Checklist.map((g) => (
              <li key={g.item} className="flex gap-2">
                <Badge tone={g.status === 'missing' ? 'bad' : 'draft'}>{g.status}</Badge>
                <span>
                  {g.item} <span className="text-meta text-ink-3">— {g.note}</span>
                </span>
              </li>
            ))}
          </ul>
        </Card>
        <Card title="12 · Project skeleton">
          {pkg.project ? (
            <Table head={['Gate', 'Phase', 'Start', 'End']} dense>
              {pkg.project.tasks.map((t) => (
                <tr key={t.id}>
                  <td className="num">{t.gate_code}</td>
                  <td>{t.name}</td>
                  <td>{fmtDate(t.start)}</td>
                  <td>{fmtDate(t.end)}</td>
                </tr>
              ))}
            </Table>
          ) : (
            <Unknown />
          )}
          <p className="mt-1 text-micro text-ink-3">{pkg.project?.provenance.note}</p>
        </Card>
      </div>
    </div>
  );
}

/** CUSTOMER INQUIRY → PRODUCT (spec §61, §139). */
export default function InquiryPage() {
  const [params] = useSearchParams();
  const nav = useNavigate();
  const engine = useEngine();
  const { records, lexicon } = useData();
  const [text, setText] = useState(params.get('text') ?? '');
  const [customerId, setCustomerId] = useState(params.get('customer') ?? '');
  const [newCustomer, setNewCustomer] = useState('');
  const [pkg, setPkg] = useState<DraftPackage | null>(null);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const customers = records.filter((r) => r.entity === 'customer');

  const ctx = useMemo(() => {
    if (!engine || !lexicon) return null;
    const of = <T,>(e: string) => records.filter((r) => r.entity === e) as unknown as T[];
    return { engine, lexicon, applications: of<Application>('application'), materials: of<Material>('material'), suppliers: of<Supplier>('supplier'), companies: of<Company>('company'), gates: of<GateDefinition>('gate_definition') };
  }, [engine, lexicon, records]);

  const analyze = () => {
    setError('');
    if (!ctx) return;
    if (text.trim().length < 12) {
      setError('Describe the inquiry in at least a sentence: part, material, process, rate, handling, inspection, integration.');
      return;
    }
    const cust = customerId || (newCustomer.trim() ? 'cus-NEW' : undefined);
    setPkg(buildDraftPackage(text.trim(), { ...ctx, customerId: cust, newId: newLocalId }));
  };

  const save = async () => {
    if (!pkg) return;
    setSaving(true);
    setError('');
    try {
      let recs: AnyRecord[] = pkg.records;
      if (!customerId && newCustomer.trim()) {
        const cid = newLocalId('customer');
        const c = { id: cid, entity: 'customer', name: newCustomer.trim(), data_type: 'USER_CREATED', provenance: { verification_status: 'DRAFT' } } as AnyRecord;
        recs = [c, ...JSON.parse(JSON.stringify(recs).replaceAll('"cus-NEW"', JSON.stringify(cid))) as AnyRecord[]];
      }
      await repo().workspace.saveMany(recs as unknown as Record<string, unknown>[], 'Created from customer inquiry');
      nav(`/record/${encodeURIComponent(pkg.opportunity.id)}`);
    } catch (e) {
      setError(`The package could not be saved: ${(e as Error).message}`);
    } finally {
      setSaving(false);
    }
  };

  return (
    <div>
      <PageHeader
        eyebrow="Flagship workflow"
        title="Create product from customer inquiry"
        subtitle="One action drafts the opportunity, requirements, application, process candidates, POC and DOE plan, architecture and reusable modules, preliminary BOM, cost assumptions, suppliers, risks, open questions, G0 checklist and project skeleton — all DRAFT until validated."
      />
      <Card className="mb-3">
        <div className="grid grid-cols-1 gap-3 lg:grid-cols-3">
          <div className="lg:col-span-2">
            <Field label="Customer inquiry (as received)" htmlFor="inq-text" error={error}>
              <Textarea id="inq-text" value={text} onChange={(e) => setText(e.target.value)} className="min-h-[110px]" placeholder="Paste the customer’s words…" />
            </Field>
            <div className="mt-1 flex flex-wrap gap-1">
              {EXAMPLES.map((e, i) => (
                <button key={i} type="button" onClick={() => setText(e)} className="rounded border border-line px-1.5 py-0.5 text-meta text-ink-3 hover:border-accent hover:text-ink">
                  Example {i + 1}
                </button>
              ))}
            </div>
          </div>
          <div className="space-y-2">
            <Field label="Customer" htmlFor="inq-cust">
              <Select id="inq-cust" value={customerId} onChange={(e) => setCustomerId(e.target.value)}>
                <option value="">— new or unknown —</option>
                {customers.map((c) => (
                  <option key={c.id} value={c.id}>
                    {c.name}
                  </option>
                ))}
              </Select>
            </Field>
            {!customerId && (
              <Field label="New customer name (optional)" htmlFor="inq-newcust">
                <Input id="inq-newcust" value={newCustomer} onChange={(e) => setNewCustomer(e.target.value)} />
              </Field>
            )}
            <div className="flex gap-2 pt-1">
              <Button variant="primary" onClick={analyze} disabled={!ctx}>
                Generate draft package
              </Button>
              {pkg && (
                <Button onClick={() => void save()} disabled={saving}>
                  {saving ? 'Saving…' : `Save ${pkg.records.length} drafts`}
                </Button>
              )}
            </div>
            {pkg?.configuration && (
              <Link className="block text-meta text-accent-2 hover:underline" to={`/configurator?product=${pkg.configuration.product_id.replace('prd-', '')}&app=${pkg.configuration.application_key ?? ''}`}>
                Open the selected platform in Configurator 2.0 →
              </Link>
            )}
          </div>
        </div>
      </Card>
      {pkg ? <PackagePreview pkg={pkg} /> : <EmptyState title="Paste an inquiry and generate the package" explain="Try Example 1 (Final demo Scenario 1: inline semiconductor package marking)." />}
    </div>
  );
}
